name: Process BIP PR

on:
  pull_request_target:
    branches:
      - main
    paths:
      - "BIPs/**"
    types:
      - labeled
jobs:
  run_reports:
    if: ${{ github.event.label.name == 'external' }}
    runs-on: ubuntu-latest
    environment: external_pr
    steps:
      - uses: "BalancerMaxis/test_external_pr_actions/.github/workflows/run_reports_reusable.yaml@main"
        # secrets: inherit
        with:
          pr_number: ${{ github.event.number }}
          checkout_ref: ${{ github.event.pull_request.head.ref }}
