name: Process BIP PR (External)

on:
  pull_request_target:
    branches:
      - main
    paths:
      - "BIPs/**"
      - "config/**"
      - "MaxiOps/**"
jobs:
  run_reports:
    uses: "BalancerMaxis/multisig-ops/.github/workflows/run_reports_reusable.yaml@main"
    secrets: inherit
    with:
      pr_number: ${{ github.event.number }}
      checkout_ref: ${{ github.event.pull_request.head.ref }}
